### ISSUE TITLE
Method 'UserLocation/get' not found

### ISSUE THREAD

**Issue by gustavlrsn** [flowkey/user-location#1]
When I try to implement this package, calling this method from the client:

`Meteor.call('UserLocation/get', function(err,res){
        console.log(err, res)
    });`

I get the error:

`errorClass {error: 404, reason: "Method 'UserLocation/get' not found", details: undefined, message: "Method 'UserLocation/get' not found [404]", errorType: "Meteor.Error"}`

Am I doing something wrong? Thanks!

**Comment by nerdmed** [comment]
@thisisgustav are you sure you have added the package?

**Comment by nerdmed** [comment]
@thisisgustav oh i am sorry - we have updated the readme and forgot to upload the new version!
UserLocation/get is only avaliable with version 2.0.0!

Just update the package to the new version and it should work!

`meteor update flowkey:user-location`
